version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
jobs:
  build:
    docker: &docker
      - image: cimg/node:10.18.1
    steps:
      - checkout
      - &setup_docker_with_caching
        setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Image
          command: |
            make build
  test:
    docker: *docker
    steps:
      - checkout
      - *setup_docker_with_caching
      - run:
          name: Run unit tests
          command: |
            touch .env
            make test
  lint:
    docker: *docker
    steps:
      - checkout
      - *setup_docker_with_caching
      - run:
          name: Check code formatting
          command: |
            make lint
  deploy:
    docker: *docker
    steps:
      - checkout
      - *setup_docker_with_caching
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image: &private-image
          image: ensemble-transposer
          tag: ${CIRCLE_TAG:-latest}
      - gcp-gcr/push-image: *private-image
workflows:
  version: 2
  ci_workflow:
    jobs: &build_jobs
      - build:
          context: data-eng-circleci-tests
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          context: data-eng-airflow-gcr
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          requires:
            - build
            - test
            - lint
